name: "Jessica Osei | Software Engineer"
author: "Jessica Osei"
description: "Hello, I'm Jessica. I'm a software engineer with an eye for design and a passion for creating great experiences with code."

# url: localhost:4000

sass:
  sass_dir: _sass

markdown: "rdiscount"
highlighter: "pygments"

# Avoid using the tab key in this file; use 2 spaces instead: http://jekyllrb.com/docs/configuration/

defaults:
-
  scope:
    path: ""
  values:
    layout: "default"

